FROM postgres:13

RUN apt-get update \
      && apt-cache showpkg postgresql-$PG_MAJOR-pgsphere \
      && apt-get install -y --no-install-recommends \
           postgresql-$PG_MAJOR-pgsphere \
      && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /docker-entrypoint-initdb.d
COPY ./initdb-pgsphere.sh /docker-entrypoint-initdb.d/pgsphere.sh