# Generated by Django 3.1.2 on 2020-10-23 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoldedLightcurve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.IntegerField()),
                ('period_length', models.FloatField()),
                ('sigma', models.FloatField()),
                ('chi_squared', models.FloatField()),
                ('classification', models.IntegerField(choices=[(1, 'Pulsator'), (2, 'EA/EB'), (3, 'EW'), (4, 'Rotator'), (5, 'Unknown'), (6, 'Junk')])),
                ('period_uncertainty', models.IntegerField(choices=[(0, 'Certain'), (1, 'Uncertain')])),
                ('classification_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superwasp_id', models.CharField(max_length=26, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZooniverseSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zooniverse_id', models.IntegerField(unique=True)),
                ('subject_set_id', models.IntegerField()),
                ('retired_at', models.DateTimeField()),
                ('image_location', models.URLField()),
                ('lightcurve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='starcatalogue.foldedlightcurve')),
            ],
        ),
        migrations.AddField(
            model_name='foldedlightcurve',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starcatalogue.star'),
        ),
    ]
