# Generated by Django 3.1.2 on 2020-10-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcatalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foldedlightcurve',
            name='classification',
            field=models.IntegerField(choices=[(1, 'Pulsator'), (2, 'EA/EB'), (3, 'EW'), (4, 'Rotator'), (5, 'Unknown'), (6, 'Junk')], null=True),
        ),
        migrations.AlterField(
            model_name='foldedlightcurve',
            name='classification_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='foldedlightcurve',
            name='period_uncertainty',
            field=models.IntegerField(choices=[(0, 'Certain'), (1, 'Uncertain')], null=True),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='image_location',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='retired_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='zooniversesubject',
            name='subject_set_id',
            field=models.IntegerField(null=True),
        ),
    ]
