# Generated by Django 3.1.2 on 2020-10-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcatalogue', '0003_auto_20201027_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foldedlightcurve',
            name='period_length',
            field=models.FloatField(null=True),
        ),
    ]
