# Generated by Django 3.1.7 on 2021-03-09 15:08

from django.db import migrations, models
import starcatalogue.models


class Migration(migrations.Migration):

    dependencies = [
        ('starcatalogue', '0005_dataexport'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataexport',
            name='export_file',
            field=models.FileField(null=True, upload_to=starcatalogue.models.export_upload_to),
        ),
    ]
