# Generated by Django 3.1.7 on 2021-03-09 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starcatalogue', '0007_auto_20210309_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataexport',
            name='order',
        ),
        migrations.RemoveField(
            model_name='dataexport',
            name='sort',
        ),
    ]
