# Generated by Django 3.1.7 on 2021-03-15 13:47

from django.db import migrations, models
import starcatalogue.models


class Migration(migrations.Migration):

    dependencies = [
        ('starcatalogue', '0008_auto_20210309_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='fits_file',
            field=models.FileField(null=True, upload_to=starcatalogue.models.star_upload_to),
        ),
    ]
