# Generated by Django 3.1.7 on 2021-03-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcatalogue', '0009_star_fits_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='fits_celery_task_id',
            field=models.UUIDField(null=True),
        ),
    ]
