# Generated by Django 3.1.7 on 2021-03-15 15:19

from django.db import migrations, models
import starcatalogue.models


class Migration(migrations.Migration):

    dependencies = [
        ('starcatalogue', '0010_star_fits_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='foldedlightcurve',
            name='image_file',
            field=models.ImageField(null=True, upload_to=starcatalogue.models.lightcurve_upload_to),
        ),
        migrations.AddField(
            model_name='foldedlightcurve',
            name='images_celery_task_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='foldedlightcurve',
            name='thumbnail_file',
            field=models.ImageField(null=True, upload_to=starcatalogue.models.lightcurve_upload_to),
        ),
    ]
