# Generated by Django 3.1.7 on 2021-03-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcatalogue', '0011_auto_20210315_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='foldedlightcurve',
            name='image_version',
            field=models.FloatField(null=True),
        ),
    ]
