# Generated by Django 3.1.7 on 2021-03-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcatalogue', '0012_foldedlightcurve_image_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='fits_celery_started',
            field=models.DateTimeField(null=True),
        ),
    ]
