# Generated by Django 3.1.7 on 2021-03-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcatalogue', '0014_dataexport_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataexport',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
    ]
