# Generated by Django 3.1.7 on 2021-03-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcatalogue', '0016_auto_20210316_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataexport',
            name='certain_period',
            field=models.BooleanField(choices=[(True, 'on'), (False, 'off')], default=True),
        ),
        migrations.AddField(
            model_name='dataexport',
            name='uncertain_period',
            field=models.BooleanField(choices=[(True, 'on'), (False, 'off')], default=True),
        ),
    ]
