# Generated by Django 3.1.7 on 2021-03-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcatalogue', '0017_auto_20210316_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='_max_magnitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='_mean_magnitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='_min_magnitude',
            field=models.FloatField(null=True),
        ),
    ]
