# Generated by Django 3.1.7 on 2021-03-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcatalogue', '0018_auto_20210316_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='foldedlightcurve',
            name='image_celery_started',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='image_celery_started',
            field=models.DateTimeField(null=True),
        ),
    ]
