# Generated by Django 3.1.7 on 2021-03-17 11:54

from django.db import migrations


def reset_magnitudes(apps, schema_editor):
    Star = apps.get_model('starcatalogue', 'Star')
    Star.objects.update(
        _mean_magnitude=None,
        _min_magnitude=None,
        _max_magnitude=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('starcatalogue', '0019_auto_20210317_1144'),
    ]

    operations = [
        migrations.RunPython(reset_magnitudes)
    ]
