# Generated by Django 3.1.7 on 2021-03-24 14:52

from django.db import migrations
import starcatalogue.fields


class Migration(migrations.Migration):

    dependencies = [
        ('starcatalogue', '0021_auto_20210324_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='location',
            field=starcatalogue.fields.SPointField(null=True),
        ),
    ]
