# Generated by Django 3.1.7 on 2021-03-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcatalogue', '0022_star_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataexport',
            name='search_radius',
            field=models.FloatField(null=True),
        ),
    ]
