# Generated by Django 3.1.7 on 2021-03-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcatalogue', '0023_dataexport_search_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='fits_error_count',
            field=models.IntegerField(default=0),
        ),
    ]
