# Generated by Django 3.2 on 2021-04-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcatalogue', '0024_star_fits_error_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataexport',
            name='max_magnitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dataexport',
            name='min_magnitude',
            field=models.FloatField(null=True),
        ),
    ]
