# Generated by Django 3.2 on 2021-04-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcatalogue', '0025_auto_20210414_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='stats_version',
            field=models.FloatField(null=True),
        ),
    ]
